### ISSUE TITLE
Make links and images work on Github (apart from the wiki)

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin-docs#136]
This is just a note for later. No action needed right away.

When viewing https://github.com/turtlecoin/turtlecoin-docs/blob/master/guides/RainBorg-Wat-Dat.md it would be nice if links like `trtlbot++` and images work. Mainly because I'm looking at that page (not the wiki) when in edit mode.

Thanks.

**Comment by Sajo811** [comment]
Problem becomes that the repos (wiki and code) become two different things, and it requires cloning of both and maintenance of links on both, rather than a simple one liner command

**Comment by SoreGums** [comment]
as soon as GitHub wiki is replaced as the front end it can :)

for now just have to push your code to wiki and edit there.

**Comment by Sajo811** [comment]
This issue can be closed right? @ZedPea @SoreGums

**Comment by SoreGums** [comment]
sure
