### ISSUE TITLE
figure out how to auto publish this to the wiki tabs

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin-docs#139]
probably can do it via travis.
will check it out over next couple days

**Comment by SoreGums** [comment]
this is probably enough

`travis.yml`
```
script:
- |
  git remote add origin-wiki https://$GITHUB_API_KEY@github.com/turtlecoin/turtlecoin-docs.wiki.git > /dev/null 2>&1 
  git remote add project-wiki https://$GITHUB_API_KEY@github.com/turtlecoin/turtlecoin.wiki.git > /dev/null 2>&1 
  git push origin-wiki HEAD:master > /dev/null 2>&1
  git push project-wiki HEAD:master > /dev/null 2>&1
env:
  matrix:
  - secure: stuff_here
```

**Comment by SoreGums** [comment]
the above works 

@RocksteadyTC please turn on travis-ci for this repo and put in a personal token with repo access to the travis control panel env vars.

I spent too long attempting to get it into the .travis.yml - it doesn't work.

**Comment by SoreGums** [comment]
I followed this it's bullshit - doesn't work...

I put the data in the travis encrypt = didn't work
put it in the control panel = works

so lame - I don't know why it didn't work.
the api endpoint for the keys doesn't exist either so I don't know what gives there....
maybe my org/repo were too new or something, checking for `key` here didn't work either so figured just do it the way that works 100% of the time and set it in the control panel.

**Comment by RocksteadyTC** [comment]
oops

**Comment by ar-x** [comment]
@RocksteadyTC Was it enabled before @SoreGums tried running `travis encrypt`?.

If not, can you:

* get the latest `turtlecoin-docs/master`.
* Run `travis encrypt GITHUB_API_KEY=YOUR_GITHUB_TOKEN --add` from the project folder.

Where the `GITHUB_API_KEY` is your personal access token with `repo` > `public_repo` access.

Let me know in case it doesn't work.

**Comment by ar-x** [comment]
It worked! Travis CI just auto deployed [a commit](https://github.com/turtlecoin/turtlecoin-docs/commit/f9661a93c468e57f2de0210828bc413daae6e22d) to the wiki.

**Comment by SoreGums** [comment]
nice one :)

glad it worked here then.

I setup a org/repo enabled in travis, wouldn't work..
https://github.com/test-org-ok/some-docs
