### ISSUE TITLE
Travis Failed

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin-docs#142]
@ar-x

https://travis-ci.org/turtlecoin/turtlecoin-docs/jobs/387311818#L407

Looks like travis went off script.

**Comment by ar-x** [comment]
@SoreGums This is super duper strange. The last two commits didn't actually trigger a CI run.

<img width="949" alt="one" src="https://user-images.githubusercontent.com/37969038/40889661-bcbe2486-671f-11e8-877a-a3441b6f2846.png">



Googling a bit

* https://github.com/travis-ci/travis-ci/issues/8632
* https://github.com/travis-ci/travis-ci/issues/8626
* https://github.com/travis-ci/travis-ci/issues/8643

**Comment by ar-x** [comment]
Thanks @ZedPea. @Sajo811 Yes a retry fixed it.

**Comment by ar-x** [comment]
sorry, i meant to ping @SoreGums not Sajo.

**Comment by Sajo811** [comment]
*insert pingsock*

**Comment by SoreGums** [comment]
maybe bed to switch to travis-ci.com since GH is all about apps now.

travis-ci.org can't do apps only travis-ci.com can and .com now supports public repos

**Comment by SoreGums** [comment]
oh, also **abuse detected** is all about miners bring detected....

it's an off/on switch zero smarts, requires an email too support

**Comment by SoreGums** [comment]
hi @RocksteadyTC please send travis support an email
https://travis-ci.org/turtlecoin/turtlecoin-docs/requests

Abuse detected.

Also turn off triggering for Pull Requests please - there is nothing to do when PR ;)


```
support@travis-ci.com

Hi,

Getting abused detected on https://travis-ci.org/turtlecoin/turtlecoin-docs/requests

All we are doing is posting the repo to the wiki tabs on two other projects/repos

Please review and tick the box that we aren't building miners to take down the travis-ci compute nodes.

Thanks.
```

**Comment by SoreGums** [comment]
hi @rocksteadytc please check if

**Build pushed branches**

is on.
we don't want `pull requests` built, however want branches built ;)

https://imgur.com/rUr7Gqv

**Comment by RocksteadyTC** [comment]
Turned BUILD PUSHED BRANCHES on

**Comment by SoreGums** [comment]
👍 finally
Thanks Rock all done with Travis setup.✌
