### ISSUE TITLE
Add error conditions to Walletd RPC documentation

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin-docs#145]
https://github.com/turtlecoin/turtlecoin-docs/blob/master/api/wallet-rpc-api.md

was requested by @ZedPea

**Comment by ZedPea** [comment]
This is a good start: https://github.com/BrandonT42/playground/blob/master/errors.md

Here's a few I can think off - i'm not sure the exact string that gets returned via walletd.

### Wrong amount
* Either the transfer amount + fee is less than the balance, or
* There are dust outputs preventing the full balance being sent (this can be rectified by using zero mixin).

Dust outputs are going to be disabled relatively soon which will alleviate this bug.

### Mixin too big or Internal Node Error
* The network can't find enough outputs to mix your transaction with. This can be rectified by using zero mixin or lowering the amount you are sending. This is very unlikely to be encountered on mainnet, and is mainly found on testnet.

I'm not sure if internal node error suggests something else as well, I have seen it only when encountering the mixin too big error.

### Network Error or Connect Error
* TurtleCoind is not open / not responding. I'm not sure if you can experience this with walletd, I have seen it with walletgreen.

### Failed add key input: key image already spent
* You are trying to send a transaction using a key image that you have already used - this can occur when your wallet is not fully synced, i.e. it is still being scanned so you are unaware that an output included in the transaction you just sent has already been used.


Hopefully that's a good start, I'm sure @BrandonT42 or @fexra probably are aware of more possible error.

You can see all the possible errors here though i'm not sure if all are returned.
* https://github.com/turtlecoin/turtlecoin/blob/master/src/Wallet/WalletErrors.h
* https://github.com/turtlecoin/turtlecoin/blob/master/src/NodeRpcProxy/NodeErrors.h
* https://github.com/turtlecoin/turtlecoin/blob/master/src/InProcessNode/InProcessNodeErrors.h

**Comment by sorenfidelis** [comment]
Is this helpful? 
I can flesh this out some more, thought I could make it a bit easier for someone to fill in data. 
- https://github.com/sorenfidelis/turtlecoin-docs/blob/master/api/rpc-api-error-conditions.md

**Comment by ZedPea** [comment]
Yeah that's pretty handy, I think i can fill out quite a few of those

**Comment by ExtraHash** [comment]
looks to be completed on #174

**Comment by Sajo8** [comment]
Unresolved, empty descriptions in https://docs.turtlecoin.lol/developer/api/rpc-api-error-conditions

**Comment by zpalmtree** [comment]
I don't think the rest are going to get filled in - It would require tracing a lot of pretty crappy code, for not much benefit when these errors are rarely seen, and turtle-service is being deprecated at some point anyway.

**Comment by zpalmtree** [comment]
Of course, if you want to take that task, feel free :smiley:

**Comment by Sajo8** [comment]
Ah true, this is turtle-service

**Comment by ExtraHash** [comment]
yes, let's please not have year old issues still open as it makes my eyeball twitch
