### ISSUE TITLE
Import Python walletd RPC examples to docs

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin-docs#157]
See https://github.com/ar-x/turtlecoin-api-docs-site/issues/4

tl;dr

Add Python walletd RPC usage examples from https://github.com/turtlecoin/turtlecoin-walletd-rpc-python to https://github.com/turtlecoin/turtlecoin-docs/blob/master/api/wallet-rpc-api.md

and get it reviewed from @arthurk.

**Bounty: 80K 🐢**

**Comment by ar-x** [comment]
@arthurk, @timmcleod I've started a bounty on this.

**Comment by timmcleod** [comment]
Anyone working on this yet @ar-x? Going to try to tackle it tomorrow unless someone else has started on it.

**Comment by ar-x** [comment]
@timmcleod No one is. Go for it :)

**Comment by ar-x** [comment]
Also, I haven't setup auto deployment to https://api-docs.turtlecoin.lol yet (like how it was on my repos). Just rebuild https://travis-ci.org/turtlecoin/turtlecoin-api-docs-site once you have committed the docs here to deploy.

**Comment by akshayrawat** [comment]
@timmcleod – @rashedmyt just expressed interest in this, he is already looking into the library @rashedmyt feel free to submit a PR incase you already have this going. I think @timmcleod was going to start on this tomorrow, feel free to ask him for help.

**Comment by akshayrawat** [comment]
@timmcleod looks like `rashedmyt` bailed.

**Comment by rashedmyt** [comment]
@ar-x @timmcleod I have updated some of the functions in my repo. Open to suggestions

**Comment by rashedmyt** [comment]
@ar-x @timmcleod @arthurk Documentation Completed and PR opened.. Any changes are welcomed.
https://github.com/turtlecoin/turtlecoin-docs/pull/161

**Comment by rashedmyt** [comment]
Its time to close this issue I think.. @ar-x @timmcleod
