### ISSUE TITLE
Previews of auto-builds for docs

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin-docs#173]
Example: for sajodocs, i can click on the little green checkmark [here](https://github.com/turtlecoin/sajodocs/pull/8) and be transported to a preview build of the website with the pr merged when a pr is made in the sajodocs repo

Currently there is no such thing for api-docs and thus it's harder to check

Is there anyway this can be fixed/changed?

cc @ar-x

**Comment by Sajo8** [comment]
As the docs are now merged, and everything's in one repo, the question is now auto-builds and previews for the docs in general. 

@SoreGums mentioned making a heroku instance and setting that up somehow

I'd go with the more easier route of just setting it up on Netlify; auto-builds, auto-previews for PRs, and configures domains and https for us automatically. What do you guys think?

cc @zpalmtree

**Comment by ExtraHash** [comment]
this now is deployed so shouldn't this be closed?

**Comment by Sajo8** [comment]
No, it hasn't been deployed yet for the api-docs. I'm not sure 100% sure if it'd work, but I haven't given it a shot. Should work, though
