### ISSUE TITLE
Wiki deploy broken

### ISSUE THREAD

**Issue by ZedPea** [turtlecoin/turtlecoin-docs#197]
From travis:

```
+git remote add origin-wiki https://[secure]@github.com/turtlecoin/turtlecoin-docs.wiki.git
+git remote add project-wiki https://[secure]@github.com/turtlecoin/turtlecoin.wiki.git
+git push origin-wiki HEAD:master
To https://github.com/turtlecoin/turtlecoin-docs.wiki.git
   462d637..fcdb7ee  HEAD -> master
+git push project-wiki HEAD:master
To https://github.com/turtlecoin/turtlecoin.wiki.git
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://[secure]@github.com/turtlecoin/turtlecoin.wiki.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by Sajo8** [comment]
Maybe make it git pull before pushing

**Comment by ZedPea** [comment]
Obviously, but I imagine that would have merge conflicts. I don't know why something is pushing directly to wiki other than this.

**Comment by SoreGums** [comment]
I'll fix it soon.

Looks like an update happened on the wiki directly ;)

It's in git, so its not exactly a secret/mystery, just got to look.

Hopefully I'll had a functioning desktop later tonight. Switching to Linux, 1 week later, 5 distros later ended up on Gentoo, should have just started with Gentoo. All these other distros marketing themselves as useable out of the box distracted me :P

**Comment by Sajo8** [comment]
:t_intrigue:

**Comment by SoreGums** [comment]
Should be  fixed.
Let's all refrain from editing the wiki directly ;)
