### ISSUE TITLE
 recipe for target 'all' failed

### ISSUE THREAD

**Issue by erikson45** [turtlecoin/turtlecoin-docs#233]
[ 27%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/seal.cpp.o
[ 28%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/seed.cpp.o
[ 28%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/serpent.cpp.o
[ 28%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sha-simd.cpp.o
[ 28%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sha.cpp.o
[ 29%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sha3.cpp.o
[ 29%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/shacal2-simd.cpp.o
[ 29%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/shacal2.cpp.o
[ 29%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/shark.cpp.o
[ 30%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sharkbox.cpp.o
[ 30%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/simon-simd.cpp.o
[ 30%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/simon.cpp.o
[ 30%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/skipjack.cpp.o
[ 31%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sm3.cpp.o
[ 31%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sm4.cpp.o
[ 31%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/socketft.cpp.o
[ 31%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sosemanuk.cpp.o
[ 32%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/speck-simd.cpp.o
[ 32%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/speck.cpp.o
[ 32%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/square.cpp.o
[ 32%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/squaretb.cpp.o
[ 33%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/sse-simd.cpp.o
[ 33%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/tea.cpp.o
[ 33%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/tftables.cpp.o
[ 33%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/threefish.cpp.o
[ 33%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/tiger.cpp.o
[ 34%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/tigertab.cpp.o
[ 34%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/trdlocal.cpp.o
[ 34%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/ttmac.cpp.o
[ 34%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/tweetnacl.cpp.o
[ 35%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/twofish.cpp.o
[ 35%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/vmac.cpp.o
[ 35%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/wait.cpp.o
[ 35%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/wake.cpp.o
[ 36%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/whrlpool.cpp.o
[ 36%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/winpipes.cpp.o
[ 36%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/xtr.cpp.o
[ 36%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/xtrcrypt.cpp.o
[ 37%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/zdeflate.cpp.o
[ 37%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/zinflate.cpp.o
[ 37%] Building CXX object external/cryptopp/CMakeFiles/cryptopp-object.dir/zlib.cpp.o
[ 37%] Built target cryptopp-object
make[2]: *** No rule to make target 'external/cryptopp/CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o', needed by 'external/cryptopp/libcryptopp.a'.  Stop.
CMakeFiles/Makefile2:271: recipe for target 'external/cryptopp/CMakeFiles/cryptopp-static.dir/all' failed
make[1]: *** [external/cryptopp/CMakeFiles/cryptopp-static.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zpalmtree** [comment]
Oh, and this is the wrong repo. You're looking for https://github.com/turtlecoin/turtlecoin . But whatever, we'll go with it for now, just use that one in future.
