### ISSUE TITLE
Remove the Cloud Mining Page

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/turtlecoin-docs#247]
I recently followed the instructions to mine on Google Cloud. The instructions worked perfectly, but within the hour Google shut it down because it violates their terms of service. I tried it a couple of times in different zones to make sure :) So, I do not think it is necessary to keep it up for people to try when Google will shut it down pretty quickly.

**Comment by Sajo8** [comment]
It violates the ToS if you don’t use a CC and use their free trial. If you input ur cc they wont shut you down

**Comment by afterconnery** [comment]
Huh I did input my CC and they shut me down.

**Comment by Sajo8** [comment]
So it seems they updated their ToS, now it says:

```
4.2 Other Suspension. Notwithstanding Section 4.1 (AUP Violations) Google may immediately Suspend all or part of Customer's use of the Services if: (a) Google believes Customer's or any Customer End User's use of the Services could adversely impact the Services, other customers' or their end users' use of the Services, or the Google network or servers used to provide the Services, which may include use of the Services for _cryptocurrency mining without Google's prior written approval_; (b) ...
```
under the [general tos](https://cloud.google.com/terms/) instead of just the [free trial terms](https://cloud.google.com/terms/free-trial/). guess it has to be removed
