### ISSUE TITLE
Need cready new Turtlecoin file and add code in current code turtle coin code.

### ISSUE THREAD

**Issue by BittraderCore** [turtlecoin/turtlecoin-docs#253]
Hi. I have exchange. 
I need create new file turtlecoin same as cryptonote is created and in current file need add turtlecoin codes as well. I upload files in zip
And add what I cryptonote php file what I need to generating to turtle coin
You can found in zip file cryptonote.class.php

[Application.zip](https://github.com/turtlecoin/turtlecoin-docs/files/3076036/Application.zip)

**Comment by Sajo8** [comment]
I assume you're looking for this https://turtlecoin.github.io/fork/

Regardless this is the wrong repo to raise an issue in. Try turtlecoin/turtlecoin maybe
