### ISSUE TITLE
Remove dedicated XMR-Stak for Linux guide?

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin-docs#268]
I made the guide a while back, as a paid project ("*Sponsored by Monerise*"). The guide seems to be useless now; the documentation on the official GitHub was not great, which it now is. Additionally, the guide only covers Ubuntu (16.04) while the official GitHub has compile instructions for many more OS's	. I feel it is best to get rid of the dedicated guide, and instead point users on Linux who wish to compile XMR-Stak on their own to the guide.

Additionally, if we do this, I feel it is appropriate to do the same for Mac; there doesn't seem to be releases for macOS on the GitHub, so we could point them to the compile guide for [mac](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_macOS.md) which, I feel, will be more actively maintained. This would close #9 

Note that if we remove the dedicated guide, then both mac and linux guides would have a single small sub-heading dedicated to them on the XMR-Stak Guide, which would also help reduce clutter and confusion for new users.

Thoughts? @SoreGums @zpalmtree 

\e: [Official guide link](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Linux.md)

**Comment by ExtraHash** [comment]
i remember your guide being far clearer and better than the official one, but if the official one has now been improved then maybe it is redundant now

**Comment by Sajo8** [comment]
Looking over the two guides (offical and ours), they're both similar. However, for eg, the official one notes that you don't need to install the SDK separately. I just built xmr-stak using build instructions on the official github, worked perfectly. I suspect the official guide being bad is why I was offered the price for the guide in the first place @ExtraHash but, as you said, it's now been improved so ours is redundant.

**Comment by ExtraHash** [comment]
Sajo requested that I test the arch build instructions on the xmr-stak page and I did so, they work.

**Comment by Sajo8** [comment]
Thanks; the releases and compile instructions work great. I'll leave it open for now while I work on the rest of the mining part of the docs, if nothing's updated I'll go ahead and resolve it

**Comment by SoreGums** [comment]
I think linking to the official "how to install" then info on how to use it with TurtleCoin would be the way to go.

**Comment by Sajo8** [comment]
Yep, we’ll tell em to download/compile for their os then lead them to the config part, uniform across OS’s

**Comment by Sajo8** [comment]
Checked out the XMRig guide, that's how I'm planning to do it. The instructions for XMRig too are pretty sparse, but they work fine, and I feel that's the main thing.

**Comment by Sajo8** [comment]
I'll go ahead with it :+1:
