### ISSUE TITLE
How many mobile mining apps will we cover?

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin-docs#269]
There seem to be no shortage of crypto miners on Android:

- [AA Miner](https://play.google.com/store/apps/details?id=com.aaminer.miner.guide&hl=en_US)
- [Termux](https://play.google.com/store/apps/details?id=com.termux&hl=en_US)
- [XMR Monero Miner](https://play.google.com/store/apps/details?id=de.ludddetis.monerominer)
- [Monero Miner - RexMiner](https://play.google.com/store/apps/details?id=com.rexminer.httpswww.movil)

- [Tony Monero](https://tony-monero-a-xmr-miner.en.aptoide.com/?store_name=pathethicsdevelopers)

And probably more, given you can sideload apps on Android (like Tony Monero).

Will we keep making guides for all of these apps? They are all the same and achieve the same exact purpose, with little to no difference in between them. Giving the user so many options and confusing them is useless, recommending them to sideload an app even worse.

I propose covering a guide for just one app on each platform; one guide for a mobile miner on android, and one for iOS. That way, we're relieved of making guides for each app, and the user has a clear way of getting the miner setup

There is currently only one app anyways for iOS [here](https://itunes.apple.com/us/app/crypto-miner-for-monero-xmr/id1320235885?mt=8); I'm making a guide for it rn. I'm not sure which one is the "best" for android, and I can't test as I don't have an android phone.

I'd appreciate you guys' opinions and recommendations, thanks!

**Comment by SoreGums** [comment]
I've only used the termux/xmrig. I wouldn't have bothered with fiddling on Android if that guide wasn't written.

I don't get the confusion angle. If people don't want to read and comprehend then why are they seeking out docs that require reading and comprehension? 

These guides don't have a limit. People contribute whatever works for them and maybe someone else finds it interesting. They ought to be curated/organised to maximise usefulness. I don't see that being "delete everything and only keep one of each kind"

**Comment by Sajo8** [comment]
Ofc there's no limit; what I"m saying is that a majority of these apps are the same, or very similar, and there is no point in making detailed guides for each and every one of them. It's only worth keeping a few select ones, which look and work well, rather than including every single app possible for the user to download. I think it's best to focus and highlight a select few apps which we've seen work well (or the only app available on the platform) and make detailed guides on those; we could add a small list of other alternatives maybe, but that would come after the detailed intro and links to the other guides for the "better" apps

**Comment by ExtraHash** [comment]
looks to have been decided to only include termux based on #271
