### ISSUE TITLE
Should each question in the FAQ show up in the ToC?

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtlecoin-docs#272]
Docusaurus, as of now, does not render H4's and below in the TOC. In this case, that means we can create individually-linkable questions in the FAQ without cluttering up the TOC on the right. Should we do that?

Current: ![image.png](https://i.postimg.cc/yNkGVvm7/image.png)
New: ![image.png](https://i.postimg.cc/Qtc0tPHZ/image.png)

thoughts?

**Comment by BebopTC** [comment]
I think each question should NOT be in the ToC. Too much.

**Comment by BebopTC** [comment]
If the FAQ eventually grows to a point that it is broken into sections, maybe linking each section would be ok, but I think each question would just make the ToC way too busy

**Comment by Sajo8** [comment]
Resolved in 4b0bc751d3f4d9b7e8948b03103d3660d7befbfb
