### ISSUE TITLE
there should be a landing page for the guides

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-docs#279]
currently on mobile, if you click the "guides" link from the main page, you get this

![Screenshot_20190723-165630](https://user-images.githubusercontent.com/35851667/61752956-e9abcd80-ad6a-11e9-957d-ad4906c3ee05.jpg)

it's a little jarring, on first impression it feels like i've been taken to the "Mining" section when i've clicked "Guides." I think it would be good to have a little landing page saying "Here are all of the guides, you can navigate them using the navigation on the left, etc."

**Comment by Sajo8** [comment]
+1, also need to find a betrr place for the FAQ

**Comment by ExtraHash** [comment]
perhaps the FAQ could get its own icon on the main page?

**Comment by Sajo8** [comment]
As in another one of these? https://i.imgur.com/9LwN0ik.jpg

**Comment by ExtraHash** [comment]
No, i'm talking about these

![image](https://user-images.githubusercontent.com/35851667/61839345-71b4d480-ae4a-11e9-8a5c-80ff52a4d896.png)

**Comment by Sajo8** [comment]
I"ll play around with the layout and see how it looks, I'll post a ss on this thread with how it looks later

**Comment by Sajo8** [comment]
FAQ is now in top title bar so I'm happy with its current position. I couldn't get it to look nice on the front page though, so I'm abandoning that idea. Still need to make the landing page for the guides though

**Comment by Sajo8** [comment]
no

**Comment by brandonlehmann** [comment]
Won’t fix. Closing.
