### ISSUE TITLE
Add an "edit" button that automatically forks the docs repo and edits the page

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-docs#281]
GitHub already has an icon for this, i was thinking we could try and add something like this directly to the docs page that would hook up to the same link

![image](https://user-images.githubusercontent.com/35851667/61997679-70f68b00-b062-11e9-9c19-a68a749b1ca3.png)

**Comment by Sajo8** [comment]
9a550ae3a2cf807b7f0e4c7736f293d866442ea0 adds this, thank you!
