### ISSUE TITLE
add github "stale" bot

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-docs#295]
It seems this repo has alot of issues that get opened for discussion, etc. and then just get forgotten about and left open

I suggest we install this github bot to automatically mark issues as stale / close them after a specified period of inactivity:

https://github.com/apps/stale

**Comment by zpalmtree** [comment]
No objection here

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/63532691-d35f7180-c4d0-11e9-8b72-9cdb710e20fb.png)

**Comment by ExtraHash** [comment]
resolved by @RocksteadyTC  and in d46a6db
