### ISSUE TITLE
Updating mining guides for chukwa

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-docs#299]
At the very least we should take down the existing guides and point to new miners if no time is available to write new guides

**Comment by SoreGums** [comment]
termux/android is done #297

**Comment by zpalmtree** [comment]
nice

**Comment by Sajo8** [comment]
what's the status on this? @SoreGums @zpalmtree @ExtraHash

**Comment by ExtraHash** [comment]
I believe we're all waiting for you to delete all the erroneous line breaks from in between the unordered and ordered list items so we can merge it @zpalmtree

**Comment by Sajo8** [comment]
Important tbd, dont close

**Comment by ExtraHash** [comment]
If you're going to keep reopening this, can you fix your PR so we can merge it?
