### ISSUE TITLE
Remove trtlbot++ docs

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-docs#325]
No longer needed with new bot

**Comment by l33d4n** [comment]
I can remove the page, but what do you want to do with existing content?
There is useful information there that is still relevant to the existing bot.
Maybe it is more correct to rename the page to the existing bot?

For example:
- Registering your Wallet
- Checking your Balance
- Tipping People
- etc.

https://docs.turtlecoin.lol/guides/using-trtlbot-plus-plus

**Comment by RocksteadyTC** [comment]
sounds good to me

**Comment by l33d4n** [comment]
Great, I have 2 questions to get started:

1. What is the name of the new page to change to?
2. What to do with the content paragraph for wallet security? (remove it completely?)

https://docs.turtlecoin.lol/guides/using-trtlbot-plus-plus#security-of-trtlbots-tipjar-wallet
<hr>

![image](https://user-images.githubusercontent.com/8020386/92346684-10100200-f100-11ea-88a8-62ce9e2cb6d8.png)

**Comment by RocksteadyTC** [comment]
The bots name is just TIPBOT

**Comment by RocksteadyTC** [comment]
since that last passage is no longer relevant, i have no opinions on whether it is labeled as deprecated or outright removed, both are fine with me
