### ISSUE TITLE
Outdated guide: Optimizing Mining on a RPi

### ISSUE THREAD

**Issue by l33d4n** [turtlecoin/turtlecoin-docs#328]
The guide is outdated and includes a lot of errors.

Tested on Raspberry Pi 3 B+ and Ubuntu Server 20.04

URL: https://docs.turtlecoin.lol/guides/mining/optimizing-rpi-turtlecoin-mining

**Comment by 0des** [comment]
whoever wrote this guide should be sudo-beaten with a sudo-baseball bat
