### ISSUE TITLE
How To Mine TurtleCoin on Mac

### ISSUE THREAD

**Issue by LAMike310** [turtlecoin/turtlecoin-docs#9]
1) Install xmr-stak
 ```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install cmake openssl hwloc libmicrohttpd
git clone https://github.com/fireice-uk/xmr-stak.git
cd xmr-stak
cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCUDA_ENABLE=OFF .
make install
```
2) Start the miner with `./bin/xmr-stak`

`xmr-stak` will ask you a few questions:

`- Currency: 'monero' or 'aeon'` : *monero*
`- Pool address:`
		Choose the closest pool to your location:
- z-pool.com:3333 *(EU North)*
- hk.turtlepool.space:3333 *(Hong Kong)*
- pool.turtleco.in:3333 *(USA West Coast)*
- auspool.turtleco.in:3333 *(AUS)*
- eu.turtlepool.space:3333 *(UK)*
- us.turtlepool.space:3333 *(USA South)*
- ny.minetrtl.us:3333 *(USA NYC)*
- turtle.atpool.party:3333 *(France)*
- slowandsteady.fun:3333
- trtl.mine2gether.com:3335

Username (wallet address or pool login): *Your TRTL address*

Password (mostly empty or x): *x*

Does this pool port support TLS/SSL?: *N*

Do you want to use nicehash?: *N*

Do you want to use multiple pools? (y/n): *Y*

Add all of the pools listed above, and give them all a weight of 10 if you're tired of reading, or if you want the best experience, give the pools nearest to you a higher number, and the ones further from you a lower number.

To check your balance as you're mining, go to the URL of the first pool your put on your list and type your wallet address into the search box in the middle of the page and it will show you how much you've mined so far.

![Mining Pool Stats Website](https://user-images.githubusercontent.com/34389545/34903526-17cf3536-f7f9-11e7-98fd-580bdcf3faed.png)

You can also see how far until the next payout by clicking "payments" at the top of the screen.

![Check miner payouts](https://user-images.githubusercontent.com/34389545/34903536-36bb8904-f7f9-11e7-8b92-d886ba15bdc5.png)

When it asks for "Username" just type in your TRTL wallet address. If you don't want to sync a blockchain and make your wallet later, you can make a paper wallet here http://turtlecoin.lol/wallet

You made it! Thanks for helping out TurtleCoin with your hashing power.

If you run into any problems, come ask a question on our Discord channel http://chat.turtlecoin.lol

**Comment by ZedPea** [comment]
Someone has already written a mac guide here - https://github.com/turtlecoin/docs/blob/master/turtlecoin-mac-guide.md - could we perhaps merge the two and add to the wiki?

**Comment by ar-x** [comment]
@LAMike310 can this issue be closed? Or does this add more to the current guide?

**Comment by Sajo811** [comment]
Can someone confirm if this works?

**Comment by Sajo811** [comment]
Going in commit history, this is the guide I found: https://github.com/turtlecoin/turtlecoin-docs/blob/b7464f0611c9f8a79b3d4b577a1453f43a7c341a/turtlecoin-mac-guide.md

**Comment by ExtraHash** [comment]
closing as duplicate guide and stale issue
